### ISSUE TITLE
Download translations does not respect languages_mapping

### ISSUE THREAD

**Issue by spacecowboy** [PaulGregor/crowdin-cli#3]
I have a crowdin.yaml with the following mapping:

```yaml
files:
  -                                                                                                                                                                                          
    source: '/src/main/res/values/strings.xml'
    translation: '/src/main/res/values-%android_code%/%original_file_name%'
    languages_mapping:
      android_code:
        # we need this mapping since Crowdin expects directories                                                                                                                             
        # to be named like "values-uk-rUA"                                                                                                                                                   
        # acording to specification instead of just "uk"                                                                                                                                     
        af: af
        ar: ar
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        et: et
        fa: fa
        fr: fr
        he: he
        hu: hu
        id: id
        it: it
        iw: iw
        ja: ja
        ko: ko
        nb: nb
        nl: nl
        pl: pl
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        tr: tr
        vi: vi
        uk: uk
        en: en
        no: no
```

Upload works, it correctly uploads the strings.xml files for all existing languages.

On download however, it does not map the codes and subsequently creates about 20 new directories with incorrect codes:

Example of existing directories:

* values-sk
* values-sl
* values-sv

Example of newly created directories:

* values -sk-rSK
* values-sk-rSI
* values-sk-rSP
* values-sv-rSE
