### ISSUE TITLE
languages_mapping

### ISSUE THREAD

**Issue by nnakid** [PaulGregor/crowdin-cli#4]
only partial matches with %locale% 
I have the following lines in config file:
```yaml
  source: '/en.lproj/*.strings'
  translation: '/%locale%.lproj/%original_file_name%'
  languages_mapping:
    locale:
      # crowdin_locale: local_name
      'ru-RU': 'ru'
      'zu-ZA': 'zu'
      'zh-CN': 'zh-Hans'
      'es-ES': 'es'
```
when doing upload / download, I end up with following folders:
```
es.lproj
zh-Hans.lproj
ru-RU.lproj - this isn't matched for some reason
zu-ZA.lproj - this isn't matched for some reason
```
